### ISSUE TITLE
honest question :)

### ISSUE THREAD

**Issue by ser** [Naguissa/mobiquo_thanks#1]
Hi,
I am curious if you plan to maintain it longer term or it was a single-shot?

**Comment by Naguissa** [comment]
I've sumitted it to Tapatalk but they replied that will not waste efforts to integrate.

But I think thanks is a excellent method to save "Me too" posts, so I want this on my phpbb forum ( www.foroelectro.net ).

That said, as I also want Tapatalk integration I have te need to maintain this project. So no, it will not be a single-shot.

Maybe there's a delay between Tapatalk releases and my patched ones, but will be done ASAP.

**Comment by ser** [comment]
fantastic, as i am planning to deploy "mentions" extension to tapatalk, co i can keep on top of your work :) +1

**Comment by Naguissa** [comment]
Hello,

Only one organization thing:

I'm using master to develop current version and I create releases using <tapatalk_version-r<revision_number>. As now it's the only version, that's all.

When new Tapatalk plugin version appears, I'll create a branch for OLD version and continue development on master for the new Tapatalk version (and releases will match corresponding Tapatalk version, also).

Maybe it's not needed, as it's not good practice to keep using old plugin, but I prefer to maintain the functional version. If there's anything to fix I can switch branch and fix also for older versions.

--------------------------


Mentions is also a very helpful plugin, it's available yet? Where?

Thanks.

**Comment by Naguissa** [comment]
One extra thing:

As far as I see in an overview, I can see posting ir ruled by:

<PHPBB_ROOT>/mobiquo/mbqClass/lib/write/MbqWrEtForumPost.php

If you see lines 686 to 689 it seems to use phpbb core functions.

Being so, maybe you don't need to modify mobiquo and can attach to phpbb events in order to check post's mentions.

**Comment by ser** [comment]
Thanks for suggestions - no, it's a plan only - the extension is here: 

https://github.com/paul999/mention

Currently after installing mentions I have set in tapatalk settings to ignore it:

`'/\[mention\](.*?)\[\/mention\]/si', '[b]$1[/b]'`
