### ISSUE TITLE
PHP Fatal error:  Uncaught InvalidArgumentException: Cannot load XML: Extra content at the end of the document

### ISSUE THREAD

**Issue by k1epto** [Naguissa/mobiquo_thanks#2]
Due to the Tapatalk custom emojis I'm seeing errors in my php logs. See below:

```
 PHP Fatal error:  Uncaught InvalidArgumentException: Cannot load XML: Extra content at the end of the document
  in /public_html/vendor/s9e/text-formatter/src/Renderer.php:23
 Stack trace:
 #0 /public_html/vendor/s9e/text-formatter/src/Renderers/PHP.php(127): s9e\TextFormatter\Renderer->loadXML('<r><QUOTE autho...')
 #1 /public_html/vendor/s9e/text-formatter/src/Renderer.php(31): s9e\TextFormatter\Renderers\PHP->renderRichText('<r><QUOTE autho...')
 #2 /public_html/phpbb/textformatter/s9e/renderer.php(250): s9e\TextFormatter\Renderer-render('<r><QUOTE autho...')
 #3 /public_html/includes/functions_content.php(600): phpbb\textformatter\s9e\renderer-render('<r><QUOTE autho...')
 #4 /public_html/viewtopic.php(1732): generate_text_for_display('<r><QUOTE autho...', '1m8xy6t2', 'gA==', 3, true)
 #5 {main}
  thrown in /public_html/vendor/s9e/text-formatter/src/Renderer.php on line 23

```
Here is the text, for some reason it added a bunch of emojis or didn't parse them properly or something... 

```
<r><QUOTE author="jordyl[emoji813]ves"><s>[quote="jordyl[emoji813]ves"]</s><QUOTE author="republique"><s>[quote="republique"]</s>I can't believe she's not still a virgin, peepler are dethperate.<e>[/quote]</e></QUOTE>
 
Don't listen to society, you don't have to be attractive to get dick.<e>[/quote]</e></QUOTE>

She doesn't particularly look human, let alone attractive lol</r>
```

I figured I should ask you first, since you modified the Tapatalk extension that I'm currently using to provide the Thanks feature to my Tapatalk integration. If you have any thoughts, I'd appreciate any information you can provide.

Thanks!

**Comment by k1epto** [comment]
A possible solution? 

https://www.tapatalk.com/groups/tapatalksupport/viewtopic.php?f=96&t=43975

**Comment by Naguissa** [comment]
I'll try to replicate asap, but it's something strange returned error: 

Extra content at the end of the document

**Comment by k1epto** [comment]
After implementing the solution here: https://www.tapatalk.com/groups/tapatalksupport/viewtopic.php?f=96&t=43975

I have not had an error since 15:59:38 UTC .... I think that was it and not anything of yours. Feel free to close this issue as you see fit.

**Comment by Naguissa** [comment]
No, no; I've to implement it, even if it's not my version fault!

Thanks for the repport and the solution!

**Comment by Naguissa** [comment]
Oh, I see! It's the extension, not the mobiquo_thanks folder.

So thanks for the info, It will be very useful for anyone with this problem.

But this means I have no work to do, hurray!

Cheers!
